### ISSUE TITLE
Some Cyrillic letters are not printed in the terminal

### ISSUE THREAD

**Issue by dimvu** [TeraTermProject/teraterm#856]
Hello, some Cyrillic letters are not displayed correctly in the terminal (large "Ш" and "Х"). After testing the encoding settings, the large "Х" letter began to display correctly, but the "Ш" letter still does not print or display. Small caps are displayed correctly and are all displayed in the terminal

<img width="641" height="36" alt="Image" src="https://github.com/user-attachments/assets/ddb3563b-ded3-4993-9aa3-00785ce1e7b0" />
<img width="314" height="124" alt="Image" src="https://github.com/user-attachments/assets/e28bd7a5-6f27-4353-839f-f7211b3b76f1" />
<img width="629" height="734" alt="Image" src="https://github.com/user-attachments/assets/9fbc846e-10b1-418d-96ef-54bf9602e294" />

**Comment by zmatsuo** [comment]
Printing with Unicode API seems implementable.
(It won't be ready for the 5.5.0 release #765.)
Please wait until implementation is complete.

**Comment by dimvu** [comment]
I installed other compatible fonts just to see if it would help, but it didn't. So it's not a font issue. Thank you, and we're looking forward to seeing the changes implemented.

**Comment by zmatsuo** [comment]
Hi
We implemented printing using Unicode API (#815).
Please try this binary.
https://github.com/TeraTermProject/teraterm/actions/runs/17880601432

**Comment by dimvu** [comment]
Good afternoon! In the assembly teraterm-5.6.0-dev-x64-20250920_224923-cbc81bb-runneradmin-snapshot 
with a capital letter "Ш"  nothing has changed, and it still doesn't print from the keyboard. Encoding Settings "DEC Special Graphics" I tried to change it, but the result doesn't change. 
<img width="647" height="27" alt="Image" src="https://github.com/user-attachments/assets/34c771ad-84e2-433a-bd1b-af112f34ce77" />
<img width="783" height="737" alt="Image" src="https://github.com/user-attachments/assets/a38ce67f-fafc-4d9b-b653-dff347c8e409" />
<img width="768" height="624" alt="Image" src="https://github.com/user-attachments/assets/871e2561-be33-4e56-bc00-28ccd9d8f713" />

**Comment by zmatsuo** [comment]
This is an image I tested on my PC.

<img width="663" height="543" alt="Image" src="https://github.com/user-attachments/assets/0e1a54e9-0b62-4ce6-8b38-e7dd3891047f" />

``` bash
for i in $(seq 0xe0 0xff); do printf "\\x$(printf '%x' $i)"; done ; echo ; for i in $(seq 0xc0 0xdf); do printf "\\x$(printf '%x' $i)"; done; echo
```

Could you try the Unicode API?

**Comment by dimvu** [comment]
according to your settings screenshots, it didn't work

<img width="511" height="436" alt="Image" src="https://github.com/user-attachments/assets/091b8d37-8274-472e-9662-9ee9f1460312" />
<img width="803" height="840" alt="Image" src="https://github.com/user-attachments/assets/0c6b006e-ffa1-4133-97c0-a3d374ba682c" />
<img width="790" height="624" alt="Image" src="https://github.com/user-attachments/assets/6a1653c1-b728-44ab-b0df-869c5571aa1a" />
<img width="509" height="33" alt="Image" src="https://github.com/user-attachments/assets/8f7a8977-ba02-4cc9-bb15-6c45942ef361" />

[TERATERM.zip](https://github.com/user-attachments/files/22589921/TERATERM.zip)
or send me your config file where everything works
Cyrillic starts working properly when transmitting cp866

**Comment by zmatsuo** [comment]
Cyrillic characters were displayed using your TERATERM.ini.
It may be font issue..?

Please try the following font.
- Lucida Console
- Consolas
- [HackGen](https://github.com/yuru7/HackGen)


HackGen
↓ CP1251

<img width="585" height="403" alt="Image" src="https://github.com/user-attachments/assets/59a72bea-c94d-46b1-b6f4-6a05ab37ee61" />

↑ CP866

**Comment by dimvu** [comment]
<img width="630" height="470" alt="Image" src="https://github.com/user-attachments/assets/bde4d7ee-7730-4770-8927-6b5bf19eec57" />
<img width="628" height="612" alt="Image" src="https://github.com/user-attachments/assets/b4abe91d-6540-4a68-9ac5-c23beb75d86c" />
<img width="628" height="340" alt="Image" src="https://github.com/user-attachments/assets/a3612771-56db-4ae2-8c04-9bdc04939459" />

Thanks, the font helped.

**Comment by zmatsuo** [comment]
Installer sets "Terminal" font when install.
This font might not be good.

Thank you.

**Comment by nmaya** [comment]
In Japanese Windows, "Terminal" font has "Japanese" and "OEM/DOS" charset.

<img width="504" height="400" alt="Image" src="https://github.com/user-attachments/assets/6202bd12-4460-4cb8-847c-df08a0951dea" />


Your font settins is [here](https://github.com/TeraTermProject/teraterm/issues/856#issuecomment-3327665522).

| Terminal (0,-19) 255

It doesn't seem like the Cyrillic charset was selected, because Cyrillic charset is 204.
We are not using a Russian version of Windows.
What charsets are available with "Terminal" font on Russian Windows?
Does the character display change when you select the Cyrillic charset with the "Terminal" font?

**Comment by zmatsuo** [comment]
When displayed using charmap.exe in Japanese Windows 10, Terminal font does not appear to be a Unicode font.

<img width="555" height="586" alt="Image" src="https://github.com/user-attachments/assets/312ab3e8-dd31-44bb-93a4-49c58c5997a8" />
